name: Rust
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install aarch64 toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: aarch64-unknown-none
      - name: Create dummy payload
        run: dd if=/dev/zero of=payload.bin bs=1024 count=1024
      - name: Build for QEMU
        run: make build.qemu
      - name: Run clippy
        run: make clippy

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Format Rust code
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install aarch64 toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: aarch64-unknown-none
          components: llvm-tools
      - name: Install QEMU
        run: |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends qemu-system-arm ipxe-qemu
      - name: Install cargo-binutils
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binutils
      - name: Prepare QEMU
        run: sudo chown $(whoami):$(whoami) /dev/vhost-vsock && sudo chmod g+rw /dev/vhost-vsock
      - name: Run the tests
        run: make test
